management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httptrace, busrefresh

spring:
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local

  cloud:
    config:
      name: damda-gateway

  config:
    import: optional:configserver:http://localhost:8888/
    #    import: configserver:http://ec2-13-124-159-0.ap-northeast-2.compute.amazonaws.com:8888/
